### PR TITLE
Rework and Zik 2.0 implementation.

### PR DESCRIPTION
**Pull request by serathius**
Tested on ubuntu 15.04
Big changes so please test other platforms.

### CODE REVIEW

**Comment by m0sia** [comment]
Hi Marek!

:+1: You are the man! You did many things in proper way so anyone's eyes will not bleed looking at my python. So thanks for your efforts! I will test it on old ubuntu(i still have 12.04) and windows7 with Zik1, than merge it with the upstream.

Regards,
Dima

**Comment by serathius** [comment]
ty, Tried to leave zik 1.0 compatibility, so that can be also tested.
I prepared resource manager layer to run only socket reading thread, to allow instant handling of notifications.

**Comment by serathius** [comment]
@m0sia 
I got problems with setting noise control.
It has two atributes "type" and "value"
type has values: "off", "anc", "aoc"
value: "1", "2"
I have no problem with value interpretation,  but I cant find any method of setting them.
I know that "/api/audio/noise_control/enabled" and "/api/audio/noise_cancellation/enabled" can set it on and off.

**Comment by serathius** [comment]
Any progress with testing?

**Comment by gauv20** [comment]
Hello,
Does this version works on ubuntu 15.10 ? I tried it but it doesn't work. First I have to type "phyton ./parrot_zik_tray" to run the program and parrot_zik_tray.py must be in /home/xxx/ and the folder is in /home/xxx/parrot_zik/.
The the program run but nothing happends. No error then I can't help. But there is the pyc files.
Thanks for your help.

**Comment by serathius** [comment]
@gauv20 Try running:
```shell
python setup install
parrot_zik_tray
```

**Comment by gauv20** [comment]
sudo python setup install

And it's work great ! Just noise control doesn't work.

Great job man !

**Comment by serathius** [comment]
Sorry, I thought that all features were functional, when I stopped developing my fork. I returned my headphones (unfortunately my glasses were tearing stites on the cups). I don't have any way of testing. But maybe I can help, if I'm provided with more information. I would be grateful If you could do some testing. Would be nice to finally merge this.

**Comment by gauv20** [comment]
No problem. But I don't have errors... The noise control command are grey and I can't then select them.
Thanks for your help !

**Comment by edouardoyallon** [comment]
Hi, do you have any suggestions for mac os X el captain? I've been able to add light blue and to slightly change the "setup.py", and then I get the following error: "ImportError: No module named bluetooth". I guess it's linked to light blue? Thanks for suggestions! Amazing work btw.

**Comment by PsycheEYE** [comment]
@gauv20 Hi, i added functionality to change noise cancellation mode, it works perfectly with ubuntu 14.04 and my Parrot Zik with 2.05 firmware version

**Comment by m0sia** [comment]
Did anyone tested this changes with the Zik 1.0?

**Comment by m0sia** [comment]
Marek,

I tested it with Zik 1.0 and it works perfectly on old Linux Mint(based on 12.04) and on ubuntu 14.04. Thanks for all your efforts!

Regards,
Dima

**Pull request merged**
